s/android-4.19: remove CONFIG_FHANDLE=n requirement
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    For config CONFIG_FHANDLE, value = y but required n
: Success